OLED_ENABLE = yes
OLED_DRIVER = SSD1306   # Enables the use of OLED displays
ENCODER_ENABLE = no       # Enables the use of one or more encoders
RGBLIGHT_ENABLE = yes      # Enable keyboard RGB underglow
COMBO_ENABLE = no
VIA_ENABLE = yes
VIAL_ENABLE = yes
QMK_SETTINGS = no
LTO_ENABLE = yes
NKRO_ENABLE = no
KEY_LOCK_ENABLE = no
KEY_OVERRIDE_ENABLE = no
SPACE_CADET_ENABLE = no
MAGIC_ENABLE = no
GRAVE_ESCAPE_ENABLE = no
MOUSEKEY_ENABLE = no
TAP_DANCE_ENABLE = no
UNICODE_ENABLE = no
COMMAND_ENABLE = no
EXTRAFLAGS += -flto
